version: '3.7'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - .:/api
    depends_on:
      - mysql
    # user: "10001:"

  # Dependencies
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  vendor: {}
